### ISSUE TITLE
shit code (major issue)

### ISSUE THREAD

**Issue by GrayAi0** [OceanicJS/Oceanic#121]
https://github.com/OceanicJS/Oceanic/blame/ed8fd59e371b4770ed7e584c44d2bd43987153bc/lib/gateway/Shard.ts#L1408

**Comment by GrayAi0** [comment]
WHAT WERE YOU THINKING???

**Comment by GrayAi0** [comment]
@DonovanDMC what do you have to say about this?

**Comment by GrayAi0** [comment]
explain ur self

**Comment by GrayAi0** [comment]
<img width="555" alt="image" src="https://github.com/OceanicJS/Oceanic/assets/48690308/717411c7-c032-43c3-b189-74869cc998e0">
<img width="688" alt="image" src="https://github.com/OceanicJS/Oceanic/assets/48690308/f7996d09-05af-4044-b668-dbf9f1087423">
even my boy chatgpt agrees

**Comment by DonovanDMC** [comment]
fuck off
