### ISSUE TITLE
Process errors when trying to access CommandInteraction#guild when app is not installed in that guild

### ISSUE THREAD

**Issue by TheFallenSpirit** [OceanicJS/Oceanic#150]
### Current Behaviour:

When attempting to access [CommandInteraction#guild](https://docs.oceanic.ws/v1.10.0/classes/CommandInteraction.html#guild), if the app is not installed in that guild, you will receive the following error:

```txt
UncachedError: CommandInteraction#guild is not present if you don't have the GUILDS intent.
```
This error is even received when simply logging the interaction `console.log(interaction)`.

### Expected Behaviour:

[CommandInteraction#guild](https://docs.oceanic.ws/v1.10.0/classes/CommandInteraction.html#guild) will be null and will not error when the app is not installed and the current context is 0 (Guild).

**Comment by ray-1337** [comment]
The error message was pretty obvious, you need to enable the **Server Members Intent** on your [Discord app](https://discord.com/developers/applications).

![image](https://github.com/OceanicJS/Oceanic/assets/33544674/a118f69d-0d2e-4108-849f-b98b06a59fcf)

**Comment by DonovanDMC** [comment]
Could you mock up a script to setup the conditions to reproduce this? I'm having trouble following what's being said here

**Comment by TheFallenSpirit** [comment]
> Could you mock up a script to setup the conditions to reproduce this? I'm having trouble following what's being said here

I don't think a script is needed, the following code should do it:

```ts
const client = new Client({
    gateway: { intents: 38571, maxShards: 'auto' },
    auth: `Bot <TOKEN-HERE>`,
});

client.on('interactionCreate', (int) => console.log(int));
client.connect();
```

Make sure the interaction has the integration types 0 and 1, and make sure it has contexts 0, 1, and 2. Then run the command in a guild that does not have the bot installed.

This is the code of my command:
```ts
import { ChatCmdRun, CmdInfo } from '@/interfaces/Command';
import { OptType } from '@/types';

export const run: ChatCmdRun = async (client, interaction) => {
    return console.log(interaction);
};

export const info: CmdInfo = {
    name: 'profile',
    cooldown: 15,
    contexts: [0, 1, 2],
    integrationTypes: [0, 1],
    description: 'View a users profile.',
    options: [
        {
            name: 'user',
            required: false,
            type: OptType.User,
            description: 'The user to view the profile of.'
        }
    ]
};
```

**Comment by DonovanDMC** [comment]
I can't reproduce this with just logging the interaction
If you're using some specific logging that inspects the object and shows hidden properties/inspects getters, your problem lies there

**Comment by TheFallenSpirit** [comment]
I investigated further, it appears my command handler was checking for the existence of the guild property on CommandInteraction. To replicate this issue use `console.log(interaction.guild)`, as that will trigger the error, but only in guilds that do not have the bot installed.

**Comment by DonovanDMC** [comment]
That isn't a bug, the guild property is defined as always returning a guild, if it can't find a guild to return, it has to throw an error

I can't test it at this exact moment, but [guildPartial](https://docs.oceanic.ws/v1.10.1/classes/CommandInteraction.html#guildPartial) is probably present

**Comment by Nonolanlan1007** [comment]
I'm currently experiencing the same issue, and the `guildPartial` property is identical whether the interaction is from a user install or a guild install.

The only difference I could spot in the `CommandInteraction` object is the `authorizingIntegrationOwners` property:
```js
// Guild Install
{ '0': 'guildIdHere', '1': 'userIdHere' }

// User Install
{ '1': 'userIdHere' }
```

I wrote this function to check if the interaction is from a guild install:
```js
function is_from_guild_install(interaction) {
  return interaction.authorizingIntegrationOwners["0"] === interaction.guildID;
}
```

I agree with @TheFallenSpirit, `interaction.guild` should be `null` if no guild can be returned. But if you absolutely want to throw an error, a different message would be better.
