### ISSUE TITLE
Second parameter is required for the threadUpdate event

### ISSUE THREAD

**Issue by Christian-Toney** [OceanicJS/Oceanic#20]
![image](https://user-images.githubusercontent.com/37517470/192040999-058347aa-e193-4fae-ad36-1df3ec75281f.png)

![image](https://user-images.githubusercontent.com/37517470/192043170-5bd33e22-cb27-45cc-bfc6-93e0990b2646.png)

**Comment by Christian-Toney** [comment]
@DonovanDMC What's the solution for this issue? It was just marked as not planned without any explanation

**Comment by DonovanDMC** [comment]
The solution is to use both parameters
