### ISSUE TITLE
What about builders 

### ISSUE THREAD

**Issue by jaw0r3k** [OceanicJS/Oceanic#30]
It would be cool to use them instead of objects

**Comment by Jam-Manbo** [comment]
they wont add built in builders, but you can still use builders package for it.
check community-resources channel in discord server.
fyi, https://npm.im/@oceanicjs/builders

**Comment by DonovanDMC** [comment]
Nothing of the sorts will be integrated into the lib itself, [external libraries](https://npm.im/@oceanicjs/builders) exist and more can be made.
