### ISSUE TITLE
Unable to suppress embeds with Message.edit due to inheriting other properties.

### ISSUE THREAD

**Issue by Cynosphere** [OceanicJS/Oceanic#32]
To suppress embeds, the API only wants `flags`. Channels.editMessage inherits `allowed_mentions`, `attachments`, `content` and `files`.

**Comment by DonovanDMC** [comment]
What? Suppressing embeds works just fine

**Comment by Cynosphere** [comment]
On other users messages?

**Comment by DonovanDMC** [comment]
That would have been useful information to lead with
