### ISSUE TITLE
Follow standard naming conventions of properties for creating messages

### ISSUE THREAD

**Issue by Cynosphere** [OceanicJS/Oceanic#39]
Its annoying to have to figure out that things like `icon_url` are named as `iconURL`

**Comment by Cynosphere** [comment]
Okay but why?

**Comment by DonovanDMC** [comment]
This is how the lib is designed, and it isn't changing. Reading the docs clearly shows how everything works.

**Comment by Cynosphere** [comment]
I don't get why its not closely following what the API sends back like Eris used to.

**Comment by Cynosphere** [comment]
It's just annoying that there is no other library like Eris that's actively maintained, and I basically have no choice but to use Oceanic but so many of your stupid design decisions just leave me frustrated.

**Comment by coolcalcacol** [comment]
use eris, or one of it's forks then?

**Comment by Cynosphere** [comment]
Eris has been unmaintained for months though and I haven't seen any forks worth anything being talked about.

Everyone I know that was using Eris moved to Oceanic, and so did I.

**Comment by Nuckyz** [comment]
Eris did the same thing as us, they just forgot to do it for some things

**Comment by DonovanDMC** [comment]
Eris was a mess of snake case and camel case, they didn't "follow standards", they just didn't follow their own style and couldn't change it due to major breaking changes later

**Comment by DonovanDMC** [comment]
If you don't like it, you are more than welcome to find a different library. It isn't changing.
