### ISSUE TITLE
Already exported a member named 'Activity'. Consider explicitly re-exporting to resolve the ambiguity.

### ISSUE THREAD

**Issue by ghost** [OceanicJS/Oceanic#41]
Hi, when I run my bot (typescript) I get this error from your package:

```
node_modules/oceanic.js/dist/lib/types/index.d.ts:9:1 - error TS2308: Module "./gateway" has already exported a member named 'Activity'. Consider explicitly re-exporting to resolve the ambiguity.

9 export * from "./guilds";
  ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/oceanic.js/dist/lib/types/index.d.ts:9
```

**Comment by doomestee** [comment]
That's been patched (https://github.com/OceanicJS/Oceanic/commit/c1c435f6d55559fdfaa0da2f3bd665ad9fc29120)
However this has not been released yet, so you might have to use the dev branch if you need it now, or wait for Donovan to release the next version.
