### ISSUE TITLE
VoiceState and embeds parsing

### ISSUE THREAD

**Issue by ghost** [OceanicJS/Oceanic#6]
VoiceState#channel is always null/uncached when the bot is started

**Comment by ghost** [comment]
one more thing the embeds still only work with snake_case

**Comment by Nuckyz** [comment]
> one more thing the embeds still only work with snake_case

Fixed already in the dev branch, not in NPM yet

**Comment by ghost** [comment]
I guess in #createInteractionResponse it should return an empty array instead of undefined if there are no embeds/components
![Screenshot (69)](https://user-images.githubusercontent.com/78654491/188297769-41187a3f-889f-4ea9-981c-324d747dbbe9.png)

**Comment by DonovanDMC** [comment]
It doesn't make a difference

**Comment by ghost** [comment]
ik but everywhere it's an empty array so yeah

**Comment by ghost** [comment]
> VoiceState#channel is always null/uncached when the bot is started

anything about this?

**Comment by DonovanDMC** [comment]
Fixed in 24f353f19febad152f8bcb100b0bd7d894f61d56

**Comment by ghost** [comment]
> Fixed in [a2b9f54](https://github.com/OceanicJS/Oceanic/commit/a2b9f54e349f943d096631a6ed5f5098457e28bc)

There is a console.log on the top, remove it
